tap "hashicorp/tap"
tap "leoafarias/fvm"
tap "nozomi-koborinai/tap"

brew "act"
brew "bash-completion"
brew "zstd"
brew "openjdk"
brew "cloud-sql-proxy"
brew "cocoapods", link: false
brew "codex"
brew "dart-sdk"
brew "deno"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "imagemagick"
brew "go"
brew "googleworkspace-cli"
brew "lazygit"
brew "neovim"
brew "opa"
brew "pandoc"
brew "stylua"
brew "tree"
brew "uv"
brew "hashicorp/tap/terraform"
brew "leoafarias/fvm/fvm"
brew "nozomi-koborinai/tap/gcp-cost-mcp-server"

brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"

cask "claude-code@latest", args: { adopt: true }
cask "drawio", args: { adopt: true }
cask "font-geist-mono-nerd-font"
cask "gcloud-cli"
cask "hammerspoon"
cask "karabiner-elements", args: { adopt: true }
cask "ngrok"
cask "wezterm@nightly"
